name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest

    env:
      APILAYER_KEY: dummy-key
      API_HOST: 0.0.0.0
      API_PORT: 5000
      API_PREFIX: /api
      HASH_SALT_ROUNDS: 10
      JWT_EXPIRES_IN: 3600
      JWT_ISSUER: dummy-issuer
      JWT_SECRET: dummy-secret
      LOG_LEVEL: debug
      NODE_ENV: development
      BRIGHT_TARGET_URL: http://0.0.0.0:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Install SecTester
      run: npm i --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Copy .env.sample to .env
      run: cp .env.sample .env

    - name: Start application
      run: npm run dev &

    - name: Wait for application to be ready
      run: |
        echo "Waiting for application to be ready..."
        until curl -s http://localhost:5000/api/health | grep '"status":"ok"'; do
          sleep 5
        done

    - name: Run security tests
      env:
        BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
        BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
        BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node --test .brightsec/tests/*.test.ts --experimental-transform-types --test-concurrency=4
