name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest

    env:
      APILAYER_KEY: your_apilayer_key
      API_HOST: localhost
      API_PORT: 5000
      API_PREFIX: /api
      HASH_SALT_ROUNDS: 10
      JWT_EXPIRES_IN: 1h
      JWT_ISSUER: your_jwt_issuer
      JWT_SECRET: your_jwt_secret
      LOG_LEVEL: info
      NODE_ENV: development
      BRIGHT_TARGET_URL: http://localhost:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Install SecTester
      run: npm i --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Copy .env.sample to .env
      run: npm run create:env

    - name: Start application
      run: |
        npm run dev &
        until wget --spider --tries=1 --retry-connrefused http://127.0.0.1:5000; do sleep 1; done

    - name: Run security tests
      env:
        BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
        BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
        BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node --experimental-transform-types --experimental-strip-types --test .brightsec/tests/*.test.ts --test-concurrency=4
