name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest

    env:
      APILAYER_KEY: dummy-key
      API_HOST: 0.0.0.0
      API_PORT: 5000
      API_PREFIX: /api
      HASH_SALT_ROUNDS: 10
      JWT_EXPIRES_IN: 3600
      JWT_ISSUER: dummy-issuer
      JWT_SECRET: dummy-secret
      LOG_LEVEL: debug
      NODE_ENV: development
      BRIGHT_TARGET_URL: http://0.0.0.0:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Install SecTester
      run: npm i --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Create .env file
      run: npm run create:env

    - name: Start application
      run: npm run dev &

    - name: Wait for application to be ready
      run: |
        for i in {1..30}; do
          if nc -zv 0.0.0.0 5000; then
            echo "Application is ready!"
            exit 0
          fi
          echo "Waiting for application to be ready..."
          sleep 2
        done
        echo "Application failed to start in time."
        exit 1

    - name: Run security tests
      env:
        BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
        BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
        BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node --experimental-transform-types --experimental-strip-types --test .brightsec/tests/*.test.ts --test-concurrency=4
